name: ChunkHopper
main: cc.ranmc.hopper.Main
description: '桃花源定制24k纯钛合金超级无敌终终终终极版的漏斗箱子插件'
website: https://www.ranmc.cc/
author: Ranica
version: Release 3.10
api-version: "1.13"
folia-supported: true

permissions: 
  ch.admin:
    default: op
    description: 'admin only'

commands:
  ch:
    description: ch
    usage: /<command>

  chunkhopper:
    description: chunkhopper
    usage: /<command>
